package database

import (
	"database/sql"
	"fmt"
)

// Insert PaymentTerm inserta datos en PAYMENT_TERM asociados a PARTY_ID.
func InsertPaymentTerm(db *sql.DB) error {
	query := `
	INSERT INTO PAYMENT_TERM (
		PARTY_ID, PAYMENT_TYPE_ID, CREDIT_CARD_ID, CURRENCY_ID, ACCOUNT_NBR,
		INTER_ACCOUNT_NBR, EXPIRATION, PAYMENT_KEY, REQUIRES_RECEIPT, BANK_ID,
		BANK_BRANCH_ID, PERIOD_ID, FIRSTNAME, LASTNAME, SECOND_LASTNAME, RUT,
		ACCOUNT_TYPE_ID, COMMUNE_ID, EMPLOYEER_ADDRESS, EMPLOYEER_CONTACT_PHONE,
		EMPLOYEER_CONTACT_NAME, ORGANIZATION_ACTIVITY, FIRST_PRIME_DPP_PAYMENT
	)
	SELECT
		p.PARTY_ID,
		CASE t.DESCTPCONDCOBRO
			WHEN 'CARGO A CUENTA' THEN 2000 -- PAC
			WHEN 'CARGO A TARJETA' THEN 3000 -- PAT
			WHEN 'COBRO DIRECTO' THEN 1000 -- DIRECTO
			ELSE NULL
		END AS PAYMENT_TYPE_ID,
		CASE
			WHEN t.DESCTPCONDCOBRO = 'CARGO A TARJETA' THEN 1 -- Simula ID de tarjeta
			ELSE NULL
		END AS CREDIT_CARD_ID,
		3000 AS CURRENCY_ID,              -- CLP
		t.NROCONDCOBRO AS ACCOUNT_NBR,    -- Número de cuenta o tarjeta
		NULL AS INTER_ACCOUNT_NBR,
		CASE
			WHEN t.DESCTPCONDCOBRO = 'CARGO A TARJETA' THEN '2028-10-01 00:00:00'
			ELSE NULL
		END AS EXPIRATION,
		NULL AS PAYMENT_KEY,
		NULL AS REQUIRES_RECEIPT,
		CASE t.IDCONDCOBRO
			WHEN 'CHILE' THEN 1
			WHEN 'INTER' THEN 2
			WHEN 'ESTADO' THEN 3
			WHEN 'SCOTIA' THEN 4
			WHEN 'CREDIT' THEN 5
			WHEN 'CORP' THEN 6
			WHEN 'BICE' THEN 7
			WHEN 'SANTAN' THEN 8
			WHEN 'ITAU' THEN 9
			WHEN 'SECUR' THEN 10
			WHEN 'FALABE' THEN 11
			WHEN 'BBVA' THEN 13
			ELSE NULL
		END AS BANK_ID,
		1 AS BANK_BRANCH_ID,             -- Valor por defecto
		CASE t.IDPERIODPAGO
			WHEN '004' THEN 1000  -- MENSUAL
			WHEN '005' THEN 2000  -- TRIMESTRAL
			WHEN '006' THEN 3000  -- SEMESTRAL
			WHEN '007' THEN 4000  -- ANUAL
			WHEN '008' THEN 5000  -- PRIMA UNICA
			ELSE NULL
		END AS PERIOD_ID,
		NULL AS FIRSTNAME,
		NULL AS LASTNAME,
		NULL AS SECOND_LASTNAME,
		NULL AS RUT,
		NULL AS ACCOUNT_TYPE_ID,
		NULL AS COMMUNE_ID,
		NULL AS EMPLOYEER_ADDRESS,
		NULL AS EMPLOYEER_CONTACT_PHONE,
		NULL AS EMPLOYEER_CONTACT_NAME,
		NULL AS ORGANIZATION_ACTIVITY,
		0 AS FIRST_PRIME_DPP_PAYMENT
	FROM temp_polizas_data t
	JOIN CONTRACT_HEADER c ON t.NPOLIZA = c.NPOLIZA
	JOIN PARTY p ON p.PARTY_ID = c.HOLDER_PARTY_ID;
	`

	_, err := db.Exec(query)
	if err != nil {
		return fmt.Errorf("error insertando en PAYMENT_TERM: %v", err)
	}

	fmt.Println("Datos insertados correctamente en PAYMENT_TERM.")
	return nil
}
