package database

import (
	"database/sql"
	"fmt"
)

// Insert PolicyCoverageValue inserta datos en la tabla POLICY_COVERAGE_VALUE
func InsertPolicyCoverageValue(db *sql.DB) error {
	query := `
	INSERT INTO POLICY_COVERAGE_VALUE (
		INSURER_PARTY_ID,
		POLICY_ID,
		SECTION_ID,
		SUB_SECTION_ID,
		ENDORSEMENT_ID,
		IC_INSURER_PARTY_ID,
		IC_SECTION_ID,
		IC_SUB_SECTION_ID,
		IC_COVERAGE_ID,
		INSURED_AMOUNT,
		DEDUCTIBLE,
		INITIAL_COVERAGE_GRACE_PERIOD,
		FUT_PAYROLL_COVER_GRACE_PERIOD,
		INIT_COVER_GROUP_GRACE_PERIOD,
		FUT_PAYROLL_COVER_G_GRACE_PERI,
		MAXIMUM_PERIOD_OF_COVERAGE,
		REINSURED_AMOUNT,
		SALARY_MULTIPLIER,
		PREMIUM,
		BASE_PREMIUM,
		TAX_VALUE
	)
	SELECT
		1020 AS INSURER_PARTY_ID,
		t.NPOLIZA AS POLICY_ID,
		101 AS SECTION_ID,
		3000 AS SUB_SECTION_ID,
		0 AS ENDORSEMENT_ID,
		1020 AS IC_INSURER_PARTY_ID,
		101 AS IC_SECTION_ID,
		3000 AS IC_SUB_SECTION_ID,
		1 AS IC_COVERAGE_ID,
		25000 AS INSURED_AMOUNT,
		NULL AS DEDUCTIBLE,
		NULL AS INITIAL_COVERAGE_GRACE_PERIOD,
		NULL AS FUT_PAYROLL_COVER_GRACE_PERIOD,
		NULL AS INIT_COVER_GROUP_GRACE_PERIOD,
		NULL AS FUT_PAYROLL_COVER_G_GRACE_PERI,
		NULL AS MAXIMUM_PERIOD_OF_COVERAGE,
		NULL AS REINSURED_AMOUNT,
		NULL AS SALARY_MULTIPLIER,
		0.46409736 AS PREMIUM,
		0.38999736 AS BASE_PREMIUM,
		0.0741 AS TAX_VALUE
	FROM temp_polizas_data t
	WHERE t.NPOLIZA LIKE '%00' AND t.CODESTADO = '03';`

	_, err := db.Exec(query)
	if err != nil {
		return fmt.Errorf("error insertando en POLICY_COVERAGE_VALUE: %v", err)
	}

	fmt.Println("Datos insertados correctamente en POLICY_COVERAGE_VALUE.")
	return nil
}
