package database

import (
	"database/sql"
	"fmt"
)

// RequestCoverageValue inserta valores en la tabla REQUEST_COVERAGE_VALUE.
func InsertRequestCoverageValue(db *sql.DB) error {
	query := `
	INSERT INTO REQUEST_COVERAGE_VALUE (
	    REQUEST_ID,
	    IC_INSURER_PARTY_ID,
	    IC_SECTION_ID,
	    IC_SUB_SECTION_ID,
	    IC_COVERAGE_ID,
	    INSURED_AMOUNT,
	    DEDUCTIBLE,
	    INITIAL_COVERAGE_GRACE_PERIOD,
	    FUT_PAYR_COVERAGE_GRACE_PERI,
	    INIT_COVER_GROUP_GRACE_PERIOD,
	    FUT_PAYR_COVER_GR_GRACE_PERIOD,
	    MAXIMUM_PERIOD_OF_COVERAGE,
	    REINSURED_AMOUNT,
	    PREMIUM,
	    BASE_PREMIUM,
	    TAX_VALUE
	)
	SELECT
	    r.REQUEST_ID,
	    1020 AS IC_INSURER_PARTY_ID,
	    101 AS IC_SECTION_ID,
	    3000 AS IC_SUB_SECTION_ID,
	    1 AS IC_COVERAGE_ID,
	    25000 AS INSURED_AMOUNT,
	    NULL AS DEDUCTIBLE,
	    NULL AS INITIAL_COVERAGE_GRACE_PERIOD,
	    NULL AS FUT_PAYR_COVERAGE_GRACE_PERI,
	    NULL AS INIT_COVER_GROUP_GRACE_PERIOD,
	    NULL AS FUT_PAYR_COVER_GR_GRACE_PERIOD,
	    NULL AS MAXIMUM_PERIOD_OF_COVERAGE,
	    NULL AS REINSURED_AMOUNT,
	    0.46409736 AS PREMIUM,
	    0.38999736 AS BASE_PREMIUM,
	    0.0741 AS TAX_VALUE
	FROM REQUEST r
	WHERE r.CONTRACT_ID IN (
	    SELECT c.CONTRACT_ID
	    FROM CONTRACT_HEADER c
	    WHERE c.INSURER_ID = 1020
	)
	  AND r.REQUEST_STATUS_ID = 13000
	LIMIT 1;
	`

	_, err := db.Exec(query)
	if err != nil {
		return fmt.Errorf("error inserting into REQUEST_COVERAGE_VALUE: %v", err)
	}

	fmt.Println("Datos insertados en REQUEST_COVERAGE_VALUE correctamente.")
	return nil
}
